### ISSUE TITLE
Why fork this repo here?

### ISSUE THREAD

**Issue by MrHeart** [fccIkeja/Julia-Tutorial-2#1]
@KaiserPhemi I don't know why you forked this repo to our organization, rather than to your personal account.  Can you explain why you forked it here, else it'll be deleted within 24 hours?

**Comment by KaiserPhemi** [comment]
@MrHeart It's got some great books on Javascript programming which I thought might be useful for some of us but you can delete it if it's a violation of the rules.

**Comment by MrHeart** [comment]
I couldn't see any of the great books there bro.  Moreover, none of us here speaks Chinese.
So the repo is off
